### ISSUE TITLE
unable to signup

### ISSUE THREAD

**Issue by Pukhraj85** [ihtasham42/social-media-app#10]
when i try to sign up it shows a strange error in console 
MongooseError: Operation `users.findOne()` buffering timed out after 10000ms
my mongo db is working correctly i dont know why this error comes
![Screenshot from 2023-01-07 13-49-14](https://user-images.githubusercontent.com/120653585/211141251-f0eadd2b-0f90-401f-bacf-0e51c83f0566.png)

**Comment by ihtasham42** [comment]
Usually when this happens it means your MongoDB has not been set up correctly
