### ISSUE TITLE
how to build ...

### ISSUE THREAD

**Issue by PJH87** [ihtasham42/social-media-app#2]
There is an error in the mongo DB URL part.

I need ".env" file setting mongo DB

**Comment by ihtasham42** [comment]
Hang on, I will post the build instructions later today

**Comment by ihtasham42** [comment]
The installation instructions are now available on the repository's read-me file.

**Comment by PJH87** [comment]
> 이제 저장소의 read-me 파일에서 설치 지침을 사용할 수 있습니다.

Thanks
