### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by nasyx-rakeeb** [ihtasham42/social-media-app#3]
i need token to deploy this project but where do i get that token. 
and anyone please help me in deployment i need to know where to deploy it heroku, netlify, vercel or something else i am a bit confused

**Comment by ihtasham42** [comment]
Hi,

The token key is just a secret key of your choosing. I used this https://randomkeygen.com/ to generate the token key.

Also, you can deploy the whole project to Heroku.

**Comment by nasyx-rakeeb** [comment]
Thanks... can i push this whole directory to heroku

**Comment by ihtasham42** [comment]
Yeah sure, just make sure to change the ``BASE_URL`` constant in ``client/config.js`` to the link of your Heroku site

**Comment by nasyx-rakeeb** [comment]
thanks

**Comment by nasyx-rakeeb** [comment]
i tried to deploy it on heroku and it was deployed successfully, but when i opened the app i think it was not getting connected to the back-end because signup/signin and other features were not working when i tried to signup and clicked submit button nothing happens its just stuck there same is the problem with signin, and i already configured environment variables in heroku

**Comment by ihtasham42** [comment]
Hm, that's strange.

Just to make sure that this is only a Heroku issue, you are able to get it working on localhost:3000 right?

Also, could I see your config.js file in /client/config.js
