### ISSUE TITLE
 social-media-app, I can't find this folder 

### ISSUE THREAD

**Issue by ogras-yasin** [ihtasham42/social-media-app#6]
Hi 

I wanted to go at social-media-app as you write, but i can't find this folder. Do i miss something?

2.Install dependencies
cd social-media-app  
npm install

**Comment by ihtasham42** [comment]
When you clone the repo, you should see a new directory be made called "social-media-app".

**Comment by ogras-yasin** [comment]
Yes I see. Thanks, you know I am a noob 🙂
________________________________
De : Ihtasham ***@***.***>
Envoyé : mardi 26 juillet 2022 22:08
À : ihtasham42/social-media-app ***@***.***>
Cc : ogras-yasin ***@***.***>; Author ***@***.***>
Objet : Re: [ihtasham42/social-media-app] social-media-app, I can't find this folder (Issue #6)


When you clone the repo, you should see a new directory be made called "social-media-app".
